- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: ssub
      location: eastus2
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: ssub
      name: ssubVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: ssub
      name: ssubSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: ssubVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: ssub
      allocation_method: Static
      name: ssubPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: ssub
      name: ssubNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: ssub
      name: ssubNIC
      virtual_network: ssubVnet
      subnet: ssubSubnet
      public_ip_name: ssubPublicIP
      security_group: ssubNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: ssub
      name: ssubLinuxVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      network_interfaces: ssubNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
