apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssamples-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mssamples
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mssamples
        version: v1
    spec:
      containers:
      - image: ssubacr.azurecr.io/mssamples:v1
        imagePullPolicy: Always
        name: hostname
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mssamples
  name: mssamples
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: mssamples
  sessionAffinity: None
  type: LoadBalancer
