---
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
      - match_re:
          severity: '^(none|warning|critical)$'
        receiver: 'VyzvamTest'
    receivers:
      - name: 'null'
      - name: 'VyzvamTest'
        slack_configs:
          - api_url: 'https://hooks.slack.com/services/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'
            channel: '#aks-monitoring'
